### PR TITLE
Initial attic folder and complete clean up of cruft

### PR DESCRIPTION
**Pull request by zvada**

### CODE REVIEW

**Comment by djw8605** [comment]
Please do not start with a clean environment.  The reason we moved the repo, and didn't start clean, is so that we could have a history of these files.  Please modify them, or move the directories around.  But they should retain the history.

Do not use attic, this is git, no need for attic.

**Comment by zvada** [comment]
Let me explain:

I moved stuff to `attic` as working dir while comparing what's been pushed in SVN for packaging as last thing before things were moved moved to https://github.com/opensciencegrid/StashCache/bin/StashDaemon ... Now, that `bin/StashDaemon` we want to remove once this is ready: https://github.com/opensciencegrid/StashCache-Daemon. We're doing complete rework so I did working copy (moved) everything relevant for me to `attic/old-*` to:

* attic/old-svn
* attic/old-git

I plan to remove attic completely after consolidating the two into more reasonable commit of all files needed for root directory and new packaging of StashCache-Daemon ... Does that strategy sound OK? 

Maybe this pull request does not necessarily to be merged upstream and can stay in my fork until ready for merge, just wanted to keep partial progress with idea in the upstream as well. Like @bbockelm said: "Publish early, publish often. That way others can help."

**Comment by djw8605** [comment]
Well, when you moved the files, you should have used `git mv ...` so that git can just rename the file, but it will still have all it's history.

Are we doing a complete re-work?  Or are we just making edits to files?  I thought a lot would be the same, configuration files will change slightly, but not significantly.

**Comment by zvada** [comment]
Yeah, found it quicker do `git rm ...` in my fork instead of `git mv...` which would make my move clearer, understood. It's not complete re-work, I should have used different phrase - there is quite a lot to be edited in existing files, indeed. The structure is not very `rhel7` friendly nor the code of `stachcache` script. That's what I meant by re-work. Plus we'll be adding things for auth vs non-auth StashCache configuration. Anyway, I don't mind if we don't merge this pull request now, we can merge later when things do not look ugly in the follow up pull request(s).

**Comment by djw8605** [comment]
I just don't want to lose the history of the files, if it can be helped.

**Comment by zvada** [comment]
OK, understood. Should re-fetch things from upstream and sync back with my fork then? While I'd keep `attic` *temporary* as my personal preference when moving/editing/creating files.

**Comment by djw8605** [comment]
You could always just create a new branch:

    git checkout -b rework origin/master

**Comment by zvada** [comment]
True, just created in my fork and made it default.

**Pull request closed without merging**
