### PR TITLE
Various fixups

### PR DESCRIPTION
**Pull request by matyasselmeci**
This is a running PR for various minor problems we find while reviewing the instructions (and trying to set it up at Madison). We should leave this open until we're done finding problems.

Feel free to push additional commits to this branch.

### CODE REVIEW

**Comment by bbockelm** [comment]
While we're here - make sure we drop comments that are no longer relevant.  For example:
```
# Config for v2 (xrootd >v4.5.0)
```
that was relevant for the 3.3. series, but I don't think anything prior to 4.5.0 has lived in 3.4.

**Comment by matyasselmeci** [comment]
I see a comment that says `Run the authenticated instance on port 8443 (Xrootd and HTTPS)`. Is that accurate? Does authenticated stashcache really talk xrootd over port 8443?

**Comment by bbockelm** [comment]
Yes, that appears correct.

Honestly, we should think hard about having the unauthenticated side also do the same -- that way, we have one authenticated and one unauthenticated port instead of three total.

Let's make that a separate task, however.

**Comment by bbockelm** [comment]
Changes so far look good.  Given the more thorough surgery being done in #8 it might make sense to merge these relatively quickly to minimize the merge conflicts on that request.

**Comment by matyasselmeci** [comment]
Perhaps we should merge #8 first?

**Comment by matyasselmeci** [comment]
Never mind.

**Pull request merged**
