### PR TITLE
Setup origin GSI authentication.

### PR DESCRIPTION
**Pull request by bbockelm**
Still need to work out a way to generate the `/etc/xrootd/Authfile` appropriately.

The authentication setup is the same approach as for the cache server.

### CODE REVIEW

**Comment by bbockelm** [comment]
This appears to work fine at Nebraska (modulo the noted Authfile generation, which will show up in a different PR).

**Comment by matyasselmeci** [comment]
Don't you need to change the names to match the new naming?

**Comment by bbockelm** [comment]
Bah, good catch

**Comment by bbockelm** [comment]
@matyasselmeci - fixed now.

**Pull request merged**
